FROM quay.io/quarkus/centos-quarkus-maven:19.2.1 AS builder
COPY src /usr/src/app/src
COPY pom.xml /usr/src/app
USER root
RUN chown -R quarkus /usr/src/app
USER quarkus
RUN mvn -f /usr/src/app/pom.xml clean package

FROM fabric8/java-alpine-openjdk8-jre
ENV AB_ENABLED=jmx_exporter
COPY --from=builder /usr/src/app/target/lib/* /deployments/lib/
COPY --from=builder /usr/src/app/target/*-runner.jar /deployments/app.jar
EXPOSE 8080
ENTRYPOINT [ "/deployments/run-java.sh"]
