version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.native
    ports:
      - "8080:8080"
  client:
    build:
      context: ./view
      args:
        BACKEND_API_URL: 'http://localhost:8080'
    ports:
      - "80:80"
    depends_on:
      - api
